FROM maven:3.9.6-eclipse-temurin-21 AS build
COPY . .
RUN mvn clean package -DskipTests

FROM eclipse-temurin:21-jdk
coPY --from-build /target/*. jar app. Jar
EXPOSE 8080
ENTRYPOINT I"java","-jar","/app. jar"I
